# Generated by Django 5.1.1 on 2024-09-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=234, verbose_name='Название')),
                ('artist_name', models.TextField(blank=True, null=True, verbose_name='Артитс')),
                ('date', models.DateTimeField(verbose_name='Дата Выхода')),
                ('image', models.ImageField(blank=True, upload_to='images', verbose_name='Обложка')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Музыка',
                'verbose_name_plural': 'Музыка',
            },
        ),
    ]
